language: node_js
before_install:
- nvm install 6
addons:
  ssh_known_hosts: 182.92.153.2
  apt:
    packages:
    - sshpass
install:
- npm install
script: true
after_success:
- sh "./bin/deploy.sh"
branches:
  only:
  - master
env:
  global:
  - secure: JT/TyBp0JS1xJ0tEU+X1/zqGMIgHlS7YCQR3xjnPIbQ7lrGOU+VflRB6TVW3mKdTHl8+NEIF6lNtT/vqsMqk5QM1Xu3gmCIqgsvQnB7B6fLydo8kgxgCZu1K/9fB5kJDu6EXrkrQ6Sil6qOuIQxCe14dVSjPY48x+5Sy2GxhSe2rozdP9905okflfqHjc16KjjeWxAetXNvyDT1x3RIge1Jd2VVC1p6ohYuAyGCB4FsBPbLCgrxoNQao8MJfcbLoizDkVRclcgDj7a2iUJ8P1yf8ZNjROzF7IPWqPOZBpMIQgJlXezGJcfY7E+qweq/LYxOX0J1xkXq/zIy8OH17XMZjzWefOfUfXv1uIhVYs+Jk66YGH9RZ1K/V4puBLlejZucfpB9p9ZLAfrIVCxpbPlV60fpYBFqLfums2+Ek9/w44HheJFYhFrMau21bSiZoQ7aV+dVgsEAZeWhCkSPRrEJtCY0Z+qVnEmSO5IAuXgJqUWK4nuRV42y/ycVvk9QfBwWm+XtornHqWMdL17Nk9J4Fpvs80tco5hm91siByJdYLcxl7qctRdg7rYbmLRYRsoasvv+0JWvOyhhhRJQpW6IMiz9k+U/96S1HDhcuFjtmDB2eac8un2HCTsVk7g28Bc8hsqlfsof2fqjqcG6WK+NONYE7AIL2oI7wDtpWrAU=
  - secure: I+YWDFFkw0WcMkid99hda+N2fBwaf3P2Sb8YOLOUvsyqf6R5lv5L9CNBuTuHReLYOg1126opBSWJkXG5NLvYeuSUurVCC2+CKDpfwLWj1qJ0ap2euuLSFBkpCTITEf2aVwAkAC1aCdeBpq33QL9pMdVHb1b3SAByCw1DivsLHVdLFqUDLTASk4TbDNNe3m1dYP9smROT1ajYeuZmAmIQj/GyeTNoPDjtKJA64gq/7RgRDeROSfWcq3Qh+NfA7gN+Be/5HOgXBWSN9NqlNO7p8bQ3IS17nIWuiH1x88aT8lu/oWuH9XLuynrNypNWF0YKaLqtHcJqnLPsX567wfxMRLgn5VpnwzEy72Pshw+SEfcxbBYnsRPI+BmgpHF90l+s9iujnOYHmWhXrknTVMcKoNGZ7jx3JvFQFSTa3eCHlV8Y3Kqo4VBsRDYSnMvI1YdmbmCEcE/+453Ytn9D3jhZph4nvF6WCkIaT0lRge3GTTfjPi5ozJvUZnJGnsLErGksiIicw+6aVNANln7llo8c/6Xj62Vkc78+LzHWZq1Fxzq/70CqMp8wsYs84Sa+F4yuVMOJFe1HdZwZJwdhC4l2SJ65xFinE3lHW4g2JXDukyk779xg8mUqlmwq55tcnwJALP1zYvW8CMQPtAQ2WrwPHn3R09fg8jA38nY5vIMJYf8=
